# Generated by Django 6.0.2 on 2026-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_category_tickettype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='available',
            new_name='quantity_total',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='max_per_order',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
