# Generated by Django 6.0.2 on 2026-03-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='awdpay_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
