# Generated by Django 6.0.2 on 2026-02-28 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_total_amount_order_total_price_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_confirmed',
            new_name='is_used',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
