# Generated by Django 6.0.2 on 2026-03-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_is_confirmed_ticket_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets_qr/'),
        ),
    ]
