# Generated by Django 5.0.1 on 2026-02-12 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be valid (6+ digits)', regex='^(\\+\\d{1,3})?[\\d\\s\\-()]{6,}$')]),
        ),
    ]
