# Generated by Django 5.0.1 on 2026-02-18 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='otpverification',
            table=None,
        ),
    ]
