# Generated by Django 5.0.1 on 2026-02-18 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_otpverification_otp_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='otp_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='otpverification',
            old_name='is_verified',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='otp_type',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
